name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        npm install

    - name: Debug npm scripts
      run: |
        echo "Available npm scripts:" && npm run

    - name: Check Node.js and npm versions
      run: |
        node -v
        npm -v

    - name: Run tests
      run: |
        npm test

    - name: Lint code
      run: |
        npm run lint




  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy application
      run: |
        echo "Deployment step (to be implemented)"
